CREATE TABLE UTILISATEUR (
    USER_ID INT PRIMARY KEY,
    USER_NOM VARCHAR(50) NOT NULL,
    USER_MAIL VARCHAR(80) NOT NULL UNIQUE,
    USER_PASS VARCHAR(256) NOT NULL,
    USER_ROLE VARCHAR(15) NOT NULL,
    USER_ID_ANTENNE INT NOT NULL REFERENCES ANTENNE(ANTENNE_ID),
    USER_LAST_LOGIN BIGINT
);
CREATE INDEX UTILISATEUR_MAIL_UK ON UTILISATEUR (USER_MAIL);
CREATE INDEX UTILISATEUR_ANTENNE_IDX ON UTILISATEUR (USER_ID_ANTENNE);
INSERT INTO UTILISATEUR (USER_ID, USER_NOM, USER_MAIL, USER_PASS, USER_ROLE, USER_ID_ANTENNE, USER_LAST_LOGIN) VALUES (1001, 'ALICE MARTIN', 'alice@carbontrack.fr', 'HASHEDPASS1', 'ADMIN', 1, 0);
INSERT INTO UTILISATEUR (USER_ID, USER_NOM, USER_MAIL, USER_PASS, USER_ROLE, USER_ID_ANTENNE, USER_LAST_LOGIN) VALUES (1002, 'BOB DUPONT', 'bob@carbontrack.fr', 'HASHEDPASS2', 'USER', 2, 0);
