       IDENTIFICATION DIVISION.
       PROGRAM-ID. USERDAL.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WSUSER.
           05 WSUSERID           PIC 9(9).
           05 WSUSERNOM          PIC X(50).
           05 WSUSERMAIL         PIC X(80).
           05 WSUSERPASS         PIC X(256).
           05 WSUSERROLE         PIC X(15).
           05 WSUSERIDANTENNE    PIC 9(9).
           05 WSUSERLASTLOGIN    PIC 9(18).
       01 WSMAIL                 PIC X(80).
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(055) VALUE "SELECT COUNT( * ) FROM UTILISA"
OCESQL  &  "TEUR WHERE USER_MAIL = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(148) VALUE "INSERT INTO UTILISATEUR (USER_"
OCESQL  &  "ID, USER_NOM, USER_MAIL, USER_PASS, USER_ROLE, USER_ID_ANT"
OCESQL  &  "ENNE, USER_LAST_LOGIN) VALUES ( $1, $2, $3, $4, $5, $6, $7"
OCESQL  &  " )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(129) VALUE "SELECT USER_ID, USER_NOM, USER"
OCESQL  &  "_MAIL, USER_PASS, USER_ROLE, USER_ID_ANTENNE, USER_LAST_LO"
OCESQL  &  "GIN FROM UTILISATEUR WHERE USER_MAIL = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0005.
OCESQL     02  FILLER PIC X(095) VALUE "UPDATE UTILISATEUR SET USER_NO"
OCESQL  &  "M = $1, USER_PASS = $2, USER_LAST_LOGIN = $3 WHERE USER_MA"
OCESQL  &  "IL = $4".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0006.
OCESQL     02  FILLER PIC X(044) VALUE "DELETE FROM UTILISATEUR WHERE "
OCESQL  &  "USER_MAIL = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0007.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LKOPERATION            PIC X(6).
       01 LKRETURN               PIC S9(9) COMP-5.
       01 LKUSER.
           05 LKUSERID           PIC 9(9).
           05 LKUSERNOM          PIC X(50).
           05 LKUSERMAIL         PIC X(80).
           05 LKUSERPASS         PIC X(256).
           05 LKUSERROLE         PIC X(15).
           05 LKUSERIDANTENNE    PIC 9(9).
           05 LKUSERLASTLOGIN    PIC 9(18).

       PROCEDURE DIVISION USING LKOPERATION LKRETURN LKUSER.
       MAINLOGIC.
           EVALUATE LKOPERATION
               WHEN 'CREATE'
                   PERFORM CREATEUSER
               WHEN 'READ  '
                   PERFORM READUSER
               WHEN 'UPDATE'
                   PERFORM UPDATEUSER
               WHEN 'DELETE'
                   PERFORM DELETEUSER
               WHEN 'END   '
                   PERFORM ENDPROG
           END-EVALUATE.
           EXIT PROGRAM.

       CONNECTDB.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE SQLCODE TO LKRETURN
                   EXIT PARAGRAPH
               END-IF
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

       CREATEUSER.
           PERFORM CONNECTDB.
           IF LKRETURN NOT = 0
               EXIT PARAGRAPH
           END-IF.

           MOVE LKUSERMAIL TO WSMAIL.
OCESQL*    EXEC SQL
OCESQL*        SELECT COUNT(*) INTO :WSUSERID
OCESQL*        FROM UTILISATEUR
OCESQL*        WHERE USER_MAIL = :WSMAIL
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecSelectIntoOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0002
OCESQL          BY VALUE 1
OCESQL          BY VALUE 1
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.
           IF WSUSERID > 0
               MOVE -803 TO LKRETURN
               EXIT PARAGRAPH
           END-IF.

           MOVE LKUSERID TO WSUSERID.
           MOVE LKUSERNOM TO WSUSERNOM.
           MOVE LKUSERMAIL TO WSUSERMAIL.
           MOVE LKUSERPASS TO WSUSERPASS.
           MOVE LKUSERROLE TO WSUSERROLE.
           MOVE LKUSERIDANTENNE TO WSUSERIDANTENNE.
           MOVE LKUSERLASTLOGIN TO WSUSERLASTLOGIN.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO UTILISATEUR
OCESQL*        (USER_ID, USER_NOM, USER_MAIL, USER_PASS, USER_ROLE,
OCESQL*         USER_ID_ANTENNE, USER_LAST_LOGIN)
OCESQL*        VALUES
OCESQL*        (:WSUSERID, :WSUSERNOM, :WSUSERMAIL, :WSUSERPASS,
OCESQL*         :WSUSERROLE, :WSUSERIDANTENNE, :WSUSERLASTLOGIN)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERNOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 256
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERPASS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 15
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERROLE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERIDANTENNE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 18
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERLASTLOGIN
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 7
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.
           MOVE SQLCODE TO LKRETURN.

       READUSER.
           PERFORM CONNECTDB.
           IF LKRETURN NOT = 0
               EXIT PARAGRAPH
           END-IF.

           MOVE LKUSERMAIL TO WSMAIL.
OCESQL*    EXEC SQL
OCESQL*        SELECT USER_ID, USER_NOM, USER_MAIL, USER_PASS,
OCESQL*               USER_ROLE, USER_ID_ANTENNE, USER_LAST_LOGIN
OCESQL*        INTO :WSUSERID, :WSUSERNOM, :WSUSERMAIL, :WSUSERPASS,
OCESQL*             :WSUSERROLE, :WSUSERIDANTENNE, :WSUSERLASTLOGIN
OCESQL*        FROM UTILISATEUR
OCESQL*        WHERE USER_MAIL = :WSMAIL
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERNOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 256
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERPASS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 15
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERROLE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERIDANTENNE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 18
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERLASTLOGIN
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecSelectIntoOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0004
OCESQL          BY VALUE 1
OCESQL          BY VALUE 7
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.
           IF SQLCODE = 0
               MOVE WSUSERID TO LKUSERID
               MOVE WSUSERNOM TO LKUSERNOM
               MOVE WSUSERMAIL TO LKUSERMAIL
               MOVE WSUSERPASS TO LKUSERPASS
               MOVE WSUSERROLE TO LKUSERROLE
               MOVE WSUSERIDANTENNE TO LKUSERIDANTENNE
               MOVE WSUSERLASTLOGIN TO LKUSERLASTLOGIN
           END-IF.
           MOVE SQLCODE TO LKRETURN.

       UPDATEUSER.
           PERFORM CONNECTDB.
           IF LKRETURN NOT = 0
               EXIT PARAGRAPH
           END-IF.

           MOVE LKUSERMAIL TO WSMAIL.
           MOVE LKUSERNOM TO WSUSERNOM.
           MOVE LKUSERPASS TO WSUSERPASS.
           MOVE LKUSERLASTLOGIN TO WSUSERLASTLOGIN.

OCESQL*    EXEC SQL
OCESQL*        UPDATE UTILISATEUR
OCESQL*        SET USER_NOM = :WSUSERNOM,
OCESQL*            USER_PASS = :WSUSERPASS,
OCESQL*            USER_LAST_LOGIN = :WSUSERLASTLOGIN
OCESQL*        WHERE USER_MAIL = :WSMAIL
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERNOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 256
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERPASS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 18
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERLASTLOGIN
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0005
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.
           MOVE SQLCODE TO LKRETURN.

       DELETEUSER.
           PERFORM CONNECTDB.
           IF LKRETURN NOT = 0
               EXIT PARAGRAPH
           END-IF.

           MOVE LKUSERMAIL TO WSMAIL.
OCESQL*    EXEC SQL
OCESQL*        DELETE FROM UTILISATEUR
OCESQL*        WHERE USER_MAIL = :WSMAIL
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0006
OCESQL          BY VALUE 1
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.
           MOVE SQLCODE TO LKRETURN.

       ENDPROG.
OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.
           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.