       IDENTIFICATION DIVISION.
       PROGRAM-ID. GESTIONACTIVITE.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-CURSOR-OPEN         PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WS-ACTIVITE.
           05 WS-ACTIVITE-ID             PIC 9(9).
           05 WS-ACTIVITE-NOM            PIC X(50).
           05 WS-ACTIVITE-TYPE           PIC X(20).
           05 WS-ACTIVITE-IDANTENNE      PIC 9(9).
           05 WS-ACTIVITE-ANIMATEUR      PIC 9(9).
           05 WS-ACTIVITE-NBPARTICIPANTS PIC 9(9).
           05 WS-ACTIVITE-MODETRANSPORT  PIC 9(9).
           05 WS-ACTIVITE-LIEU           PIC X(100).
           05 WS-ACTIVITE-DISTANCE       PIC 9(9).
           05 WS-ACTIVITE-HEBERGEMENT    PIC 9(9).
           05 WS-ACTIVITE-REPASPREVU     PIC 9(9).
           05 WS-ACTIVITE-EMPREINTETOTALE PIC 9(13)V9(4).
       01 WS-REPAS.
           05 WS-REPAS-ID                PIC 9(9).
           05 WS-REPAS-ID-ACTIVITE       PIC 9(9).
           05 WS-REPAS-TYPE              PIC 9(9).
           05 WS-REPAS-NBREPAS           PIC 9(9).
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(256) VALUE "INSERT INTO ACTIVITE (ACTIVITE"
OCESQL  &  "_ID, ACTIVITE_NOM, ACTIVITE_TYPE, ACTIVITE_IDANTENNE, ACTI"
OCESQL  &  "VITE_ANIMATEUR, ACTIVITE_NBPARTICIPANTS, ACTIVITE_MODETRAN"
OCESQL  &  "SPORT, ACTIVITE_LIEU, ACTIVITE_DISTANCE, ACTIVITE_HEBERGEM"
OCESQL  &  "ENT, ACTIVITE_REPASPREVU, ACTIVITE_EMPREINTETOTALE) ".
OCESQL     02  FILLER PIC X(060) VALUE "VALUES ( $1, $2, $3, $4, $5, $"
OCESQL  &  "6, $7, $8, $9, $10, $11, $12 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(100) VALUE "INSERT INTO REPAS (REPAS_ID, R"
OCESQL  &  "EPAS_ID_ACTIVITE, REPAS_TYPE, REPAS_NBREPAS) VALUES ( $1, "
OCESQL  &  "$2, $3, $4 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(092) VALUE "SELECT REPAS_ID, REPAS_ID_ACTI"
OCESQL  &  "VITE, REPAS_TYPE, REPAS_NBREPAS FROM REPAS WHERE REPAS_ID "
OCESQL  &  "= $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0005.
OCESQL     02  FILLER PIC X(101) VALUE "SELECT REPAS_ID, REPAS_ID_ACTI"
OCESQL  &  "VITE, REPAS_TYPE, REPAS_NBREPAS FROM REPAS WHERE REPAS_ID_"
OCESQL  &  "ACTIVITE = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0006.
OCESQL     02  FILLER PIC X(072) VALUE "UPDATE REPAS SET REPAS_TYPE = "
OCESQL  &  "$1, REPAS_NBREPAS = $2 WHERE REPAS_ID = $3".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0007.
OCESQL     02  FILLER PIC X(037) VALUE "DELETE FROM REPAS WHERE REPAS_"
OCESQL  &  "ID = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0008.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LK-OPERATION           PIC X(10).
       01 LK-END-OF-FILE         PIC X.
       01 LK-ACTIVITE.
           05 LK-ACTIVITE-ID             PIC 9(9).
           05 LK-ACTIVITE-NOM            PIC X(50).
           05 LK-ACTIVITE-TYPE           PIC X(20).
           05 LK-ACTIVITE-IDANTENNE      PIC 9(9).
           05 LK-ACTIVITE-ANIMATEUR      PIC 9(9).
           05 LK-ACTIVITE-NBPARTICIPANTS PIC 9(9).
           05 LK-ACTIVITE-MODETRANSPORT  PIC 9(9).
           05 LK-ACTIVITE-LIEU           PIC X(100).
           05 LK-ACTIVITE-DISTANCE       PIC 9(9).
           05 LK-ACTIVITE-HEBERGEMENT    PIC 9(9).
           05 LK-ACTIVITE-REPASPREVU     PIC 9(9).
           05 LK-ACTIVITE-EMPREINTETOTALE PIC 9(13)V9(4).
       01 LK-REPAS.
           05 LK-REPAS-ID                PIC 9(9).
           05 LK-REPAS-ID-ACTIVITE       PIC 9(9).
           05 LK-REPAS-TYPE              PIC 9(9).
           05 LK-REPAS-NBREPAS           PIC 9(9).

       PROCEDURE DIVISION USING LK-OPERATION LK-END-OF-FILE
           LK-ACTIVITE LK-REPAS.
       MAIN-LOGIC.
           EVALUATE LK-OPERATION
               WHEN 'CREATEACT'
                   PERFORM CREATEACTIVITE
               WHEN 'CREATEREP'
                   PERFORM CREATEREPAS
               WHEN 'READREP'
                   PERFORM READREPAS
               WHEN 'LISTREP'
                   PERFORM LISTREPAS
               WHEN 'UPDATEREP'
                   PERFORM UPDATEREPAS
               WHEN 'DELETEREP'
                   PERFORM DELETEREPAS
               WHEN 'END'
                   PERFORM ENDPROGRAM
           END-EVALUATE.
           EXIT PROGRAM.

       CONNECTDB.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE = 0
                   MOVE 'Y' TO WS-CONNECTED
               ELSE
                   MOVE 'Y' TO LK-END-OF-FILE
               END-IF
           END-IF.

       CREATEACTIVITE.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH END-IF.

           MOVE LK-ACTIVITE TO WS-ACTIVITE.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO ACTIVITE
OCESQL*        (ACTIVITE_ID, ACTIVITE_NOM, ACTIVITE_TYPE,
OCESQL*         ACTIVITE_IDANTENNE, ACTIVITE_ANIMATEUR,
OCESQL*         ACTIVITE_NBPARTICIPANTS, ACTIVITE_MODETRANSPORT,
OCESQL*         ACTIVITE_LIEU, ACTIVITE_DISTANCE,
OCESQL*         ACTIVITE_HEBERGEMENT, ACTIVITE_REPASPREVU,
OCESQL*         ACTIVITE_EMPREINTETOTALE)
OCESQL*        VALUES
OCESQL*        (:WS-ACTIVITE-ID, :WS-ACTIVITE-NOM, :WS-ACTIVITE-TYPE,
OCESQL*         :WS-ACTIVITE-IDANTENNE, :WS-ACTIVITE-ANIMATEUR,
OCESQL*         :WS-ACTIVITE-NBPARTICIPANTS, :WS-ACTIVITE-MODETRANSPORT,
OCESQL*         :WS-ACTIVITE-LIEU, :WS-ACTIVITE-DISTANCE,
OCESQL*         :WS-ACTIVITE-HEBERGEMENT, :WS-ACTIVITE-REPASPREVU,
OCESQL*         :WS-ACTIVITE-EMPREINTETOTALE)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-NOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 20
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-IDANTENNE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-ANIMATEUR
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-NBPARTICIPANTS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-MODETRANSPORT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 100
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-LIEU
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-DISTANCE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-HEBERGEMENT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACTIVITE-REPASPREVU
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 17
OCESQL          BY VALUE -4
OCESQL          BY REFERENCE WS-ACTIVITE-EMPREINTETOTALE
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0002
OCESQL          BY VALUE 12
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       CREATEREPAS.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH END-IF.

           MOVE LK-REPAS TO WS-REPAS.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO REPAS
OCESQL*        (REPAS_ID, REPAS_ID_ACTIVITE, REPAS_TYPE, REPAS_NBREPAS)
OCESQL*        VALUES
OCESQL*        (:WS-REPAS-ID, :WS-REPAS-ID-ACTIVITE,
OCESQL*         :WS-REPAS-TYPE, :WS-REPAS-NBREPAS)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID-ACTIVITE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-NBREPAS
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       READREPAS.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH END-IF.

           MOVE LK-REPAS-ID TO WS-REPAS-ID.

OCESQL*    EXEC SQL
OCESQL*        SELECT REPAS_ID, REPAS_ID_ACTIVITE, REPAS_TYPE,
OCESQL*               REPAS_NBREPAS
OCESQL*        INTO :WS-REPAS-ID, :WS-REPAS-ID-ACTIVITE,
OCESQL*             :WS-REPAS-TYPE, :WS-REPAS-NBREPAS
OCESQL*        FROM REPAS
OCESQL*        WHERE REPAS_ID = :WS-REPAS-ID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID-ACTIVITE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-NBREPAS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecSelectIntoOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0004
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE = 0
               MOVE WS-REPAS TO LK-REPAS
           ELSE
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       LISTREPAS.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH END-IF.

           MOVE LK-REPAS-ID-ACTIVITE TO WS-REPAS-ID-ACTIVITE.

           IF WS-CURSOR-OPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CREP CURSOR FOR
OCESQL*            SELECT REPAS_ID, REPAS_ID_ACTIVITE, REPAS_TYPE,
OCESQL*                   REPAS_NBREPAS
OCESQL*            FROM REPAS
OCESQL*            WHERE REPAS_ID_ACTIVITE = :WS-REPAS-ID-ACTIVITE
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID-ACTIVITE
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorDeclareParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CREP" & x"00"
OCESQL          BY REFERENCE SQ0005
OCESQL          BY VALUE 1
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CREP
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CREP" & x"00"
OCESQL     END-CALL
               IF SQLCODE = 0
                   MOVE 'Y' TO WS-CURSOR-OPEN
               ELSE
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CREP INTO
OCESQL*            :WS-REPAS-ID, :WS-REPAS-ID-ACTIVITE,
OCESQL*            :WS-REPAS-TYPE, :WS-REPAS-NBREPAS
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID-ACTIVITE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-NBREPAS
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CREP" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE = 0
               MOVE WS-REPAS TO LK-REPAS
           ELSE
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       UPDATEREPAS.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH END-IF.

           MOVE LK-REPAS TO WS-REPAS.

OCESQL*    EXEC SQL
OCESQL*        UPDATE REPAS
OCESQL*        SET REPAS_TYPE = :WS-REPAS-TYPE,
OCESQL*            REPAS_NBREPAS = :WS-REPAS-NBREPAS
OCESQL*        WHERE REPAS_ID = :WS-REPAS-ID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-NBREPAS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0006
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       DELETEREPAS.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH END-IF.

           MOVE LK-REPAS-ID TO WS-REPAS-ID.

OCESQL*    EXEC SQL
OCESQL*        DELETE FROM REPAS
OCESQL*        WHERE REPAS_ID = :WS-REPAS-ID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-REPAS-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0007
OCESQL          BY VALUE 1
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       ENDPROGRAM.
           IF WS-CURSOR-OPEN = 'Y'
OCESQL*        EXEC SQL
OCESQL*            CLOSE CREP
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CREP" & x"00"
OCESQL     END-CALL
               MOVE 'N' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.