       IDENTIFICATION DIVISION.
       PROGRAM-ID. DISPLAY-DEPT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-DEPT-DISPLAY.
           05 FILLER PIC X(10) VALUE "DEPT ID: ".
           05 WS-DEPT-ID-DISP PIC 9(4).
           05 FILLER PIC X VALUE SPACE.
           05 FILLER PIC X(12) VALUE "DEPT NAME: ".
           05 WS-DEPT-NAME-DISP PIC X(40).
       LINKAGE SECTION.
       01 LK-DEPARTMENT.
           05 LK-DEPT-ID PIC 9(4).
           05 LK-DEPT-NAME PIC X(40).
       PROCEDURE DIVISION USING LK-DEPARTMENT.
       MAIN-LOGIC.
           MOVE LK-DEPT-ID TO WS-DEPT-ID-DISP
           MOVE LK-DEPT-NAME TO WS-DEPT-NAME-DISP
           DISPLAY WS-DEPT-DISPLAY
           EXIT PROGRAM.