       IDENTIFICATION DIVISION.
       PROGRAM-ID. EMPLOYEE-LOGIC.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       PROCEDURE DIVISION.
           *> AUTO-GENERATED HEADER for layer logic
           GOBACK.
