       IDENTIFICATION DIVISION.
       PROGRAM-ID. ACTIVITY-DAL-DB.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-CURSOR-OPEN         PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.

       01 WSUSER.
           05 WSUSERID           PIC 9(9).
           05 WSUSERNOM          PIC X(50).
           05 WSUSERMAIL         PIC X(80).
           05 WSUSERPASS         PIC X(256).
           05 WSUSERROLE         PIC X(15).
           05 WSUSERIDANTENNE    PIC 9(9).
           05 WSUSERLASTLOGIN    PIC 9(18).

       01 WSACTIVITE.
           05 WSACTIVITEID       PIC 9(9).
           05 WSACTIVITENOM      PIC X(50).
           05 WSACTIVITETYPE     PIC X(20).
           05 WSACTIVITEIDANTENNE PIC 9(9).
           05 WSACTIVITEANIMATEUR PIC 9(9).
           05 WSACTIVITENBPART   PIC 9(9).
           05 WSACTIVITEMODETRANS PIC 9(9).
           05 WSACTIVITELIEU     PIC X(100).
           05 WSACTIVITEDISTANCE PIC 9(9).
           05 WSACTIVITEHEBERG   PIC 9(9).
           05 WSACTIVITEREPAS    PIC 9(9).
           05 WSACTIVITEEMPREINTE PIC 9(13)V9(4).

       01 WSPARTICIPATION.
           05 WSPARTACTIVITEID   PIC 9(9).
           05 WSPARTUSERID       PIC 9(9).
           05 WSPARTMODETRANS    PIC 9(9).

       01 WSJOINTURE.
           05 WSJOINTACTIVITEID  PIC 9(9).
           05 WSJOINTACTIVITENOM PIC X(50).
           05 WSJOINTACTIVITETYPE PIC X(20).
           05 WSJOINTACTIVITELIEU PIC X(100).
           05 WSJOINUSERID       PIC 9(9).
           05 WSJOINUSERNOM      PIC X(50).
           05 WSJOINUSERMAIL     PIC X(80).
           05 WSJOINMODETRANS    PIC 9(9).
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(127) VALUE "INSERT INTO UTILISATEUR (USER_"
OCESQL  &  "ID, USER_NOM, USER_MAIL, USER_PASS, USER_ROLE, USER_ID_ANT"
OCESQL  &  "ENNE) VALUES ( $1, $2, $3, $4, $5, $6 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(256) VALUE "INSERT INTO ACTIVITE (ACTIVITE"
OCESQL  &  "_ID, ACTIVITE_NOM, ACTIVITE_TYPE, ACTIVITE_IDANTENNE, ACTI"
OCESQL  &  "VITE_ANIMATEUR, ACTIVITE_NBPARTICIPANTS, ACTIVITE_MODETRAN"
OCESQL  &  "SPORT, ACTIVITE_LIEU, ACTIVITE_DISTANCE, ACTIVITE_HEBERGEM"
OCESQL  &  "ENT, ACTIVITE_REPASPREVU) VALUES ( $1, $2, $3, $4, $".
OCESQL     02  FILLER PIC X(029) VALUE "5, $6, $7, $8, $9, $10, $11 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(128) VALUE "INSERT INTO PARTICIPATION (PAR"
OCESQL  &  "TICIPATION_ID_ACTIVITE, PARTICIPATION_ID_USER, PARTICIPATI"
OCESQL  &  "ON_MODE_TRANSPORT) VALUES ( $1, $2, $3 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0005.
OCESQL     02  FILLER PIC X(256) VALUE "SELECT CAST(A.ACTIVITE_NOM AS "
OCESQL  &  "VARCHAR(50)), CAST(A.ACTIVITE_TYPE AS VARCHAR(20)), CAST(A"
OCESQL  &  ".ACTIVITE_LIEU AS VARCHAR(100)), CAST(U.USER_NOM AS VARCHA"
OCESQL  &  "R(50)), CAST(U.USER_MAIL AS VARCHAR(80)), P.PARTICIPATION_"
OCESQL  &  "MODE_TRANSPORT FROM PARTICIPATION P JOIN ACTIVITE A ".
OCESQL     02  FILLER PIC X(176) VALUE "ON P.PARTICIPATION_ID_ACTIVITE"
OCESQL  &  " = A.ACTIVITE_ID JOIN UTILISATEUR U ON P.PARTICIPATION_ID_"
OCESQL  &  "USER = U.USER_ID WHERE P.PARTICIPATION_ID_ACTIVITE = $1 AN"
OCESQL  &  "D P.PARTICIPATION_ID_USER = $2".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0006.
OCESQL     02  FILLER PIC X(256) VALUE "SELECT A.ACTIVITE_ID, A.ACTIVI"
OCESQL  &  "TE_NOM, A.ACTIVITE_TYPE, A.ACTIVITE_LIEU, U.USER_ID, U.USE"
OCESQL  &  "R_NOM, U.USER_MAIL, P.PARTICIPATION_MODE_TRANSPORT FROM PA"
OCESQL  &  "RTICIPATION P JOIN ACTIVITE A ON P.PARTICIPATION_ID_ACTIVI"
OCESQL  &  "TE = A.ACTIVITE_ID JOIN UTILISATEUR U ON P.PARTICIPA".
OCESQL     02  FILLER PIC X(063) VALUE "TION_ID_USER = U.USER_ID WHERE"
OCESQL  &  " P.PARTICIPATION_ID_ACTIVITE = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0007.
OCESQL     02  FILLER PIC X(256) VALUE "SELECT A.ACTIVITE_ID, A.ACTIVI"
OCESQL  &  "TE_NOM, A.ACTIVITE_TYPE, A.ACTIVITE_LIEU, U.USER_ID, U.USE"
OCESQL  &  "R_NOM, U.USER_MAIL, P.PARTICIPATION_MODE_TRANSPORT FROM PA"
OCESQL  &  "RTICIPATION P JOIN ACTIVITE A ON P.PARTICIPATION_ID_ACTIVI"
OCESQL  &  "TE = A.ACTIVITE_ID JOIN UTILISATEUR U ON P.PARTICIPA".
OCESQL     02  FILLER PIC X(059) VALUE "TION_ID_USER = U.USER_ID WHERE"
OCESQL  &  " P.PARTICIPATION_ID_USER = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0008.
OCESQL     02  FILLER PIC X(126) VALUE "UPDATE PARTICIPATION SET PARTI"
OCESQL  &  "CIPATION_MODE_TRANSPORT = $1 WHERE PARTICIPATION_ID_ACTIVI"
OCESQL  &  "TE = $2 AND PARTICIPATION_ID_USER = $3".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0009.
OCESQL     02  FILLER PIC X(093) VALUE "DELETE FROM PARTICIPATION WHER"
OCESQL  &  "E PARTICIPATION_ID_ACTIVITE = $1 AND PARTICIPATION_ID_USER"
OCESQL  &  " = $2".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0010.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LK-OPERATION          PIC X(30).
       01 LK-END-OF-FILE        PIC X.
       01 LK-USER.
           05 LKUSERID          PIC 9(9).
           05 LKUSERNOM         PIC X(50).
           05 LKUSERMAIL        PIC X(80).
           05 LKUSERPASS        PIC X(256).
           05 LKUSERROLE        PIC X(15).
           05 LKUSERIDANTENNE   PIC 9(9).
           05 LKUSERLASTLOGIN   PIC 9(18).
       01 LK-ACTIVITE.
           05 LKACTIVITEID      PIC 9(9).
           05 LKACTIVITENOM     PIC X(50).
           05 LKACTIVITETYPE    PIC X(20).
           05 LKACTIVITEIDANTENNE PIC 9(9).
           05 LKACTIVITEANIMATEUR PIC 9(9).
           05 LKACTIVITENBPART  PIC 9(9).
           05 LKACTIVITEMODETRANS PIC 9(9).
           05 LKACTIVITELIEU    PIC X(100).
           05 LKACTIVITEDISTANCE PIC 9(9).
           05 LKACTIVITEHEBERG  PIC 9(9).
           05 LKACTIVITEREPAS   PIC 9(9).
           05 LKACTIVITEEMPREINTE PIC 9(13)V9(4).
       01 LK-PARTICIPATION.
           05 LKPARTACTIVITEID  PIC 9(9).
           05 LKPARTUSERID      PIC 9(9).
           05 LKPARTMODETRANS   PIC 9(9).
       01 LK-JOINTURE.
           05 LKJOINTACTIVITEID PIC 9(9).
           05 LKJOINTACTIVITENOM PIC X(50).
           05 LKJOINTACTIVITETYPE PIC X(20).
           05 LKJOINTACTIVITELIEU PIC X(100).
           05 LKJOINUSERID      PIC 9(9).
           05 LKJOINUSERNOM     PIC X(50).
           05 LKJOINUSERMAIL    PIC X(80).
           05 LKJOINMODETRANS   PIC 9(9).

       PROCEDURE DIVISION USING LK-OPERATION LK-END-OF-FILE
           LK-USER LK-ACTIVITE LK-PARTICIPATION LK-JOINTURE.
       MAIN-LOGIC.
           EVALUATE LK-OPERATION
               WHEN 'CREATEUSER'
                   PERFORM CREATEUSER
               WHEN 'CREATEACTIVITE'
                   PERFORM CREATEACTIVITE
               WHEN 'CREATEPARTICIPATION'
                   PERFORM CREATEPARTICIPATION
               WHEN 'READPARTICIPATION'
                   PERFORM READPARTICIPATION
               WHEN 'LISTPARTBYACT'
                   PERFORM LISTPARTBYACT
               WHEN 'LISTACTBYUSER'
                   PERFORM LISTACTBYUSER
               WHEN 'UPDATEMODETRANS'
                   PERFORM UPDATEMODETRANS
               WHEN 'DELETEPARTICIPATION'
                   PERFORM DELETEPARTICIPATION
               WHEN 'END'
                   PERFORM DALEND
           END-EVALUATE.
           EXIT PROGRAM.

       CONNECTDB.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

       CREATEUSER.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LKUSERID TO WSUSERID.
           MOVE LKUSERNOM TO WSUSERNOM.
           MOVE LKUSERMAIL TO WSUSERMAIL.
           MOVE LKUSERPASS TO WSUSERPASS.
           MOVE LKUSERROLE TO WSUSERROLE.
           MOVE LKUSERIDANTENNE TO WSUSERIDANTENNE.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO UTILISATEUR
OCESQL*        (USER_ID, USER_NOM, USER_MAIL, USER_PASS, USER_ROLE,
OCESQL*         USER_ID_ANTENNE)
OCESQL*        VALUES
OCESQL*        (:WSUSERID, :WSUSERNOM, :WSUSERMAIL, :WSUSERPASS,
OCESQL*         :WSUSERROLE, :WSUSERIDANTENNE)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERNOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 256
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERPASS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 15
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERROLE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERIDANTENNE
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0002
OCESQL          BY VALUE 6
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

       CREATEACTIVITE.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LKACTIVITEID TO WSACTIVITEID.
           MOVE LKACTIVITENOM TO WSACTIVITENOM.
           MOVE LKACTIVITETYPE TO WSACTIVITETYPE.
           MOVE LKACTIVITEIDANTENNE TO WSACTIVITEIDANTENNE.
           MOVE LKACTIVITEANIMATEUR TO WSACTIVITEANIMATEUR.
           MOVE LKACTIVITENBPART TO WSACTIVITENBPART.
           MOVE LKACTIVITEMODETRANS TO WSACTIVITEMODETRANS.
           MOVE LKACTIVITELIEU TO WSACTIVITELIEU.
           MOVE LKACTIVITEDISTANCE TO WSACTIVITEDISTANCE.
           MOVE LKACTIVITEHEBERG TO WSACTIVITEHEBERG.
           MOVE LKACTIVITEREPAS TO WSACTIVITEREPAS.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO ACTIVITE
OCESQL*        (ACTIVITE_ID, ACTIVITE_NOM, ACTIVITE_TYPE,
OCESQL*         ACTIVITE_IDANTENNE, ACTIVITE_ANIMATEUR,
OCESQL*         ACTIVITE_NBPARTICIPANTS, ACTIVITE_MODETRANSPORT,
OCESQL*         ACTIVITE_LIEU, ACTIVITE_DISTANCE, ACTIVITE_HEBERGEMENT,
OCESQL*         ACTIVITE_REPASPREVU)
OCESQL*        VALUES
OCESQL*        (:WSACTIVITEID, :WSACTIVITENOM, :WSACTIVITETYPE,
OCESQL*         :WSACTIVITEIDANTENNE, :WSACTIVITEANIMATEUR,
OCESQL*         :WSACTIVITENBPART, :WSACTIVITEMODETRANS,
OCESQL*         :WSACTIVITELIEU, :WSACTIVITEDISTANCE,
OCESQL*         :WSACTIVITEHEBERG, :WSACTIVITEREPAS)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITENOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 20
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITETYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITEIDANTENNE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITEANIMATEUR
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITENBPART
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITEMODETRANS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 100
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITELIEU
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITEDISTANCE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITEHEBERG
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITEREPAS
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 11
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

       CREATEPARTICIPATION.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LKPARTACTIVITEID TO WSPARTACTIVITEID.
           MOVE LKPARTUSERID TO WSPARTUSERID.
           MOVE LKPARTMODETRANS TO WSPARTMODETRANS.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO PARTICIPATION
OCESQL*        (PARTICIPATION_ID_ACTIVITE, PARTICIPATION_ID_USER,
OCESQL*         PARTICIPATION_MODE_TRANSPORT)
OCESQL*        VALUES
OCESQL*        (:WSPARTACTIVITEID, :WSPARTUSERID, :WSPARTMODETRANS)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTMODETRANS
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0004
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

       READPARTICIPATION.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LKPARTACTIVITEID TO WSPARTACTIVITEID.
           MOVE LKPARTUSERID TO WSPARTUSERID.

OCESQL*    EXEC SQL
OCESQL*        SELECT CAST(A.ACTIVITE_NOM   AS VARCHAR(50)),
OCESQL*            CAST(A.ACTIVITE_TYPE AS VARCHAR(20)),
OCESQL*            CAST(A.ACTIVITE_LIEU AS VARCHAR(100)),
OCESQL*            CAST(U.USER_NOM      AS VARCHAR(50)),
OCESQL*            CAST(U.USER_MAIL     AS VARCHAR(80)),
OCESQL*            P.PARTICIPATION_MODE_TRANSPORT
OCESQL*        INTO :WSJOINTACTIVITEID, :WSJOINTACTIVITENOM,
OCESQL*             :WSJOINTACTIVITETYPE, :WSJOINTACTIVITELIEU,
OCESQL*             :WSJOINUSERID, :WSJOINUSERNOM, :WSJOINUSERMAIL,
OCESQL*             :WSJOINMODETRANS
OCESQL*        FROM PARTICIPATION P
OCESQL*        JOIN ACTIVITE A ON 
OCESQL*        P.PARTICIPATION_ID_ACTIVITE = A.ACTIVITE_ID
OCESQL*        CORRECTION: RETOUR A LA LIGNE
OCESQL*        JOIN UTILISATEUR U ON P.PARTICIPATION_ID_USER = U.USER_ID
OCESQL*        WHERE P.PARTICIPATION_ID_ACTIVITE = :WSPARTACTIVITEID
OCESQL*        AND P.PARTICIPATION_ID_USER = :WSPARTUSERID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITENOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 20
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITETYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 100
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITELIEU
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERNOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINMODETRANS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecSelectIntoOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0005
OCESQL          BY VALUE 2
OCESQL          BY VALUE 8
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           DISPLAY " SQLSTATE: " SQLSTATE.
           DISPLAY " SQLERRMC: " SQLERRMC.

           IF SQLCODE = 0
               MOVE WSJOINTACTIVITEID TO LKJOINTACTIVITEID
               MOVE WSJOINTACTIVITENOM TO LKJOINTACTIVITENOM
               MOVE WSJOINTACTIVITETYPE TO LKJOINTACTIVITETYPE
               MOVE WSJOINTACTIVITELIEU TO LKJOINTACTIVITELIEU
               MOVE WSJOINUSERID TO LKJOINUSERID
               MOVE WSJOINUSERNOM TO LKJOINUSERNOM
               MOVE WSJOINUSERMAIL TO LKJOINUSERMAIL
               MOVE WSJOINMODETRANS TO LKJOINMODETRANS
           ELSE
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       LISTPARTBYACT.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LKACTIVITEID TO WSACTIVITEID.

           IF WS-CURSOR-OPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CPARTBYACT CURSOR FOR
OCESQL*            SELECT A.ACTIVITE_ID, A.ACTIVITE_NOM, 
OCESQL*                   A.ACTIVITE_TYPE,
OCESQL*        CORRECTION: RETOUR A LA LIGNE
OCESQL*                   A.ACTIVITE_LIEU,
OCESQL*                   U.USER_ID, U.USER_NOM, U.USER_MAIL,
OCESQL*                   P.PARTICIPATION_MODE_TRANSPORT
OCESQL*            FROM PARTICIPATION P
OCESQL*            JOIN ACTIVITE A ON P.PARTICIPATION_ID_ACTIVITE =
OCESQL*                A.ACTIVITE_ID
OCESQL*            JOIN UTILISATEUR U ON 
OCESQL*            P.PARTICIPATION_ID_USER = U.USER_ID
OCESQL*        CORRECTION: RETOUR A LA LIGNE
OCESQL*            WHERE P.PARTICIPATION_ID_ACTIVITE = :WSACTIVITEID
OCESQL*        CORRECTION: WSACTIVITEID
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorDeclareParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPARTBYACT" & x"00"
OCESQL          BY REFERENCE SQ0006
OCESQL          BY VALUE 1
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CPARTBYACT
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPARTBYACT" & x"00"
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CPARTBYACT INTO
OCESQL*            :WSJOINTACTIVITEID, :WSJOINTACTIVITENOM,
OCESQL*            :WSJOINTACTIVITETYPE, :WSJOINTACTIVITELIEU,
OCESQL*            :WSJOINUSERID, :WSJOINUSERNOM, :WSJOINUSERMAIL,
OCESQL*            :WSJOINMODETRANS
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITENOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 20
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITETYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 100
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITELIEU
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERNOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINMODETRANS
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPARTBYACT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE = 0
               MOVE WSJOINTACTIVITEID TO LKJOINTACTIVITEID
               MOVE WSJOINTACTIVITENOM TO LKJOINTACTIVITENOM
               MOVE WSJOINTACTIVITETYPE TO LKJOINTACTIVITETYPE
               MOVE WSJOINTACTIVITELIEU TO LKJOINTACTIVITELIEU
               MOVE WSJOINUSERID TO LKJOINUSERID
               MOVE WSJOINUSERNOM TO LKJOINUSERNOM
               MOVE WSJOINUSERMAIL TO LKJOINUSERMAIL
               MOVE WSJOINMODETRANS TO LKJOINMODETRANS
           ELSE
               MOVE 'Y' TO LK-END-OF-FILE
               MOVE 'N' TO WS-CURSOR-OPEN
           END-IF.

       LISTACTBYUSER.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LKUSERID TO WSUSERID.

           IF WS-CURSOR-OPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CACTBYUSER CURSOR FOR
OCESQL*            SELECT A.ACTIVITE_ID, A.ACTIVITE_NOM, 
OCESQL*                   A.ACTIVITE_TYPE,
OCESQL*        CORRECTION: RETOUR A LA LIGNE
OCESQL*                   A.ACTIVITE_LIEU,
OCESQL*                   U.USER_ID, U.USER_NOM, U.USER_MAIL,
OCESQL*                   P.PARTICIPATION_MODE_TRANSPORT
OCESQL*            FROM PARTICIPATION P
OCESQL*            JOIN ACTIVITE A ON P.PARTICIPATION_ID_ACTIVITE =
OCESQL*                A.ACTIVITE_ID
OCESQL*            JOIN UTILISATEUR U ON 
OCESQL*            P.PARTICIPATION_ID_USER = U.USER_ID
OCESQL*            WHERE P.PARTICIPATION_ID_USER = :WSUSERID
OCESQL*        CORRECTION: WSUSERID
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorDeclareParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CACTBYUSER" & x"00"
OCESQL          BY REFERENCE SQ0007
OCESQL          BY VALUE 1
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CACTBYUSER
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CACTBYUSER" & x"00"
OCESQL     END-CALL
               
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CACTBYUSER INTO
OCESQL*            :WSJOINTACTIVITEID, :WSJOINTACTIVITENOM,
OCESQL*            :WSJOINTACTIVITETYPE, :WSJOINTACTIVITELIEU,
OCESQL*            :WSJOINUSERID, :WSJOINUSERNOM, :WSJOINUSERMAIL,
OCESQL*            :WSJOINMODETRANS
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITENOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 20
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITETYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 100
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINTACTIVITELIEU
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERNOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 80
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINUSERMAIL
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSJOINMODETRANS
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CACTBYUSER" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE = 0
               MOVE WSJOINTACTIVITEID TO LKJOINTACTIVITEID
               MOVE WSJOINTACTIVITENOM TO LKJOINTACTIVITENOM
               MOVE WSJOINTACTIVITETYPE TO LKJOINTACTIVITETYPE
               MOVE WSJOINTACTIVITELIEU TO LKJOINTACTIVITELIEU
               MOVE WSJOINUSERID TO LKJOINUSERID
               MOVE WSJOINUSERNOM TO LKJOINUSERNOM
               MOVE WSJOINUSERMAIL TO LKJOINUSERMAIL
               MOVE WSJOINMODETRANS TO LKJOINMODETRANS
           ELSE
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       UPDATEMODETRANS.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LKPARTACTIVITEID TO WSPARTACTIVITEID.
           MOVE LKPARTUSERID TO WSPARTUSERID.
           MOVE LKPARTMODETRANS TO WSPARTMODETRANS.

OCESQL*    EXEC SQL
OCESQL*        UPDATE PARTICIPATION
OCESQL*        SET PARTICIPATION_MODE_TRANSPORT = :WSPARTMODETRANS
OCESQL*        WHERE PARTICIPATION_ID_ACTIVITE = :WSPARTACTIVITEID
OCESQL*        AND PARTICIPATION_ID_USER = :WSPARTUSERID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTMODETRANS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0008
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.
           
       DELETEPARTICIPATION.
           PERFORM CONNECTDB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LKPARTACTIVITEID TO WSPARTACTIVITEID.
           MOVE LKPARTUSERID TO WSPARTUSERID.

OCESQL*    EXEC SQL
OCESQL*        DELETE FROM PARTICIPATION
OCESQL*        WHERE PARTICIPATION_ID_ACTIVITE = :WSPARTACTIVITEID
OCESQL*        AND PARTICIPATION_ID_USER = :WSPARTUSERID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTACTIVITEID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSPARTUSERID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0009
OCESQL          BY VALUE 2
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

       DALEND.
           IF WS-CURSOR-OPEN = 'Y'
OCESQL*        EXEC SQL
OCESQL*            CLOSE CPARTBYACT
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPARTBYACT" & x"00"
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            CLOSE CACTBYUSER
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CACTBYUSER" & x"00"
OCESQL     END-CALL
               MOVE 'N' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.