       IDENTIFICATION DIVISION.
       PROGRAM-ID. DISPLAY-SUPPLIER.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-END-OF-FILE         PIC X VALUE 'N'.
OCESQL*
       LINKAGE SECTION.
       01 LK-SUPPLIER.
           05 LK-SUP-ID          PIC 9(9).
           05 LK-SUP-NAME        PIC X(50).
       PROCEDURE DIVISION USING LK-SUPPLIER.
       MAIN-LOGIC.
           DISPLAY "ID FOURNISSEUR: " LK-SUP-ID.
           DISPLAY "NOM FOURNISSEUR: " LK-SUP-NAME.
           EXIT PROGRAM.