#!/bin/bash
# Compilation script for ACTIVITE-LOGIC
# Generated by CobolSmartGen

set -e

PROGRAM="/home/mfabre/pi/cobol_generator/try/out_test_carbontrack06/logic/ACTIVITE-LOGIC.cbl"
PROGRAM_NAME="ACTIVITE-LOGIC"
OUTPUT_DIR="../bin"

echo "========================================="
echo "Compiling ${PROGRAM_NAME}..."
echo "========================================="

# Check if file exists
if [ ! -f "${PROGRAM}" ]; then
    echo "ERROR: File ${PROGRAM} not found!"
    exit 1
fi

# Create output directory
mkdir -p "${OUTPUT_DIR}"

# Compile with GnuCOBOL
echo "Running cobc..."
cobc -x -free -o "${OUTPUT_DIR}/${PROGRAM_NAME}" "${PROGRAM}"

if [ $? -eq 0 ]; then
    echo "✅ Compilation successful!"
    echo "Executable: ${OUTPUT_DIR}/${PROGRAM_NAME}"
    exit 0
else
    echo "❌ Compilation failed!"
    exit 1
fi