       IDENTIFICATION DIVISION.
       PROGRAM-ID. TEST-HEBERGEMENT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-HEBERGEMENT.
           05 WS-HEB-ID          PIC 9(9) VALUE 1.
           05 WS-HEB-ID-ACT      PIC 9(9) VALUE 1.
           05 WS-HEB-TYPE        PIC 9(4) VALUE 1.
           05 WS-HEB-NBNUIT      PIC 9(4) VALUE 2.
       01 WS-ACTIVITE.
           05 WS-ACT-ID          PIC 9(9) VALUE 1.
           05 WS-ACT-NOM         PIC X(50) VALUE "Test Activite".
           05 WS-ACT-TYPE        PIC X(20) VALUE "Sport".
           05 WS-ACT-IDANTENNE   PIC 9(9) VALUE 1.
           05 WS-ACT-ANIMATEUR   PIC 9(9) VALUE 1.
           05 WS-ACT-NBPART      PIC 9(4) VALUE 10.
           05 WS-ACT-MODETRANS   PIC 9(4) VALUE 1.
           05 WS-ACT-LIEU        PIC X(100) VALUE "Paris".
           05 WS-ACT-DISTANCE    PIC 9(9) VALUE 0.
           05 WS-ACT-HEBERG      PIC 9(9) VALUE 0.
           05 WS-ACT-REPAS       PIC 9(4) VALUE 1.
           05 WS-ACT-EMPREINTE   PIC 9(13)V9(4) VALUE 100.5.
       01 WS-OPERATION          PIC X(10).
       01 WS-END-OF-FILE        PIC X VALUE 'N'.
       01 WS-TEST-RESULT        PIC X(30).
       01 WS-FORMAT-NUM         PIC Z(8)9.

OCESQL*
       PROCEDURE DIVISION.
       MAIN-LOGIC.
           DISPLAY "DEBUT DES TESTS".

      *    TEST CREATE-ACTIVITE
           MOVE "CREATEACT" TO WS-OPERATION.
           CALL "HEBERGEMENT-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-HEBERGEMENT WS-ACTIVITE.
           IF WS-END-OF-FILE = 'N'
               DISPLAY "TEST CREATE-ACTIVITE: OK"
           ELSE
               DISPLAY "TEST CREATE-ACTIVITE: ECHEC"
           END-IF.

      *    TEST CREATE-HEBERGEMENT
           MOVE "CREATEHEB" TO WS-OPERATION.
           CALL "HEBERGEMENT-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-HEBERGEMENT WS-ACTIVITE.
           IF WS-END-OF-FILE = 'N'
               DISPLAY "TEST CREATE-HEBERGEMENT: OK"
           ELSE
               DISPLAY "TEST CREATE-HEBERGEMENT: ECHEC"
           END-IF.

      *    TEST ADD-ACTIVITE-HEBERGEMENT
           MOVE "ADDACTHEB" TO WS-OPERATION.
           CALL "HEBERGEMENT-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-HEBERGEMENT WS-ACTIVITE.
           IF WS-END-OF-FILE = 'N'
               DISPLAY "TEST ADD-ACTIVITE-HEBERGEMENT: OK"
           ELSE
               DISPLAY "TEST ADD-ACTIVITE-HEBERGEMENT: ECHEC"
           END-IF.

      *    TEST READ-HEBERGEMENT
           MOVE 1 TO WS-HEB-ID.
           MOVE "READHEB" TO WS-OPERATION.
           CALL "HEBERGEMENT-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-HEBERGEMENT WS-ACTIVITE.
           IF WS-END-OF-FILE = 'N'
               DISPLAY "TEST READ-HEBERGEMENT: OK"
               MOVE WS-HEB-ID TO WS-FORMAT-NUM
               DISPLAY "ID: " WS-FORMAT-NUM
               MOVE WS-HEB-ID-ACT TO WS-FORMAT-NUM
               DISPLAY "ID ACT: " WS-FORMAT-NUM
               MOVE WS-HEB-TYPE TO WS-FORMAT-NUM
               DISPLAY "TYPE: " WS-FORMAT-NUM
               MOVE WS-HEB-NBNUIT TO WS-FORMAT-NUM
               DISPLAY "NB NUITS: " WS-FORMAT-NUM
           ELSE
               DISPLAY "TEST READ-HEBERGEMENT: ECHEC"
           END-IF.

      *    TEST LIST-HEBERGEMENTS-ACTIVITE
           MOVE 1 TO WS-ACT-ID.
           MOVE "LISTHEBACT" TO WS-OPERATION.
           PERFORM UNTIL WS-END-OF-FILE = 'Y'
               CALL "HEBERGEMENT-DAL-DB" USING WS-OPERATION
                   WS-END-OF-FILE WS-HEBERGEMENT WS-ACTIVITE
               IF WS-END-OF-FILE = 'N'
                   DISPLAY "TEST LIST-HEBERGEMENTS-ACTIVITE: OK"
                   MOVE WS-HEB-ID TO WS-FORMAT-NUM
                   DISPLAY "ID: " WS-FORMAT-NUM
                   MOVE WS-HEB-ID-ACT TO WS-FORMAT-NUM
                   DISPLAY "ID ACT: " WS-FORMAT-NUM
                   MOVE WS-HEB-TYPE TO WS-FORMAT-NUM
                   DISPLAY "TYPE: " WS-FORMAT-NUM
                   MOVE WS-HEB-NBNUIT TO WS-FORMAT-NUM
                   DISPLAY "NB NUITS: " WS-FORMAT-NUM
               END-IF
           END-PERFORM.
           MOVE 'N' TO WS-END-OF-FILE.

      *    TEST UPDATE-HEBERGEMENT
           MOVE 1 TO WS-HEB-ID.
           MOVE 2 TO WS-HEB-TYPE.
           MOVE 5 TO WS-HEB-NBNUIT.
           MOVE "UPDATEHEB" TO WS-OPERATION.
           CALL "HEBERGEMENT-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-HEBERGEMENT WS-ACTIVITE.
           IF WS-END-OF-FILE = 'N'
               DISPLAY "TEST UPDATE-HEBERGEMENT: OK"
           ELSE
               DISPLAY "TEST UPDATE-HEBERGEMENT: ECHEC"
           END-IF.

      *    TEST AFFICHE-HEBERGEMENT
           CALL "AFFICHE-HEBERGEMENT" USING WS-HEBERGEMENT.

      *    TEST DELETE-HEBERGEMENT
           MOVE 1 TO WS-HEB-ID.
           MOVE "DELETEHEB" TO WS-OPERATION.
           CALL "HEBERGEMENT-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-HEBERGEMENT WS-ACTIVITE.
           IF WS-END-OF-FILE = 'N'
               DISPLAY "TEST DELETE-HEBERGEMENT: OK"
           ELSE
               DISPLAY "TEST DELETE-HEBERGEMENT: ECHEC"
           END-IF.

      *    FIN DES TESTS
           MOVE "END" TO WS-OPERATION.
           CALL "HEBERGEMENT-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-HEBERGEMENT WS-ACTIVITE.

           DISPLAY "FIN DES TESTS".
           STOP RUN.