       IDENTIFICATION DIVISION.
       PROGRAM-ID. PROJECT-DAL-DB.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-CURSOROPEN          PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WS-PROJID              PIC 9(9).
       01 WS-PROJNAME            PIC X(60).
       01 WS-BUDGET              PIC 9(10)V99.
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(046) VALUE "SELECT PROJ_ID, PROJ_NAME, BUD"
OCESQL  &  "GET FROM PROJECT".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(065) VALUE "UPDATE PROJECT SET PROJ_NAME ="
OCESQL  &  " $1, BUDGET = $2 WHERE PROJ_ID = $3".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(070) VALUE "INSERT INTO PROJECT (PROJ_ID, "
OCESQL  &  "PROJ_NAME, BUDGET) VALUES ( $1, $2, $3 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0005.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LK-OPERATION           PIC X(4).
       01 LK-ENDOFFILE           PIC X.
       01 LK-PROJECT.
           05 LK-PROJID          PIC 9(9).
           05 LK-PROJNAME        PIC X(60).
           05 LK-BUDGET          PIC 9(10)V99.

       PROCEDURE DIVISION USING LK-OPERATION LK-ENDOFFILE
           LK-PROJECT.
       MAINLOGIC.
           EVALUATE LK-OPERATION
               WHEN 'READ'
                   PERFORM DALREAD
               WHEN 'SAVE'
                   PERFORM DALSAVE
               WHEN 'END '
                   PERFORM DALEND
           END-EVALUATE.
           EXIT PROGRAM.

       DALREAD.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-ENDOFFILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

           IF WS-CURSOROPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CPROJ CURSOR FOR
OCESQL*            SELECT PROJ_ID, PROJ_NAME, BUDGET
OCESQL*            FROM PROJECT
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorDeclare" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPROJ" & x"00"
OCESQL          BY REFERENCE SQ0002
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CPROJ
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPROJ" & x"00"
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-ENDOFFILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CURSOROPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CPROJ INTO
OCESQL*            :WS-PROJID,
OCESQL*            :WS-PROJNAME,
OCESQL*            :WS-BUDGET
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PROJID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 60
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PROJNAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 12
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-BUDGET
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPROJ" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-ENDOFFILE
           ELSE
               MOVE WS-PROJID        TO LK-PROJID
               MOVE WS-PROJNAME      TO LK-PROJNAME
               MOVE WS-BUDGET        TO LK-BUDGET
           END-IF.

       DALSAVE.
           MOVE LK-PROJID        TO WS-PROJID.
           MOVE LK-PROJNAME      TO WS-PROJNAME.
           MOVE LK-BUDGET        TO WS-BUDGET.

OCESQL*    EXEC SQL
OCESQL*        UPDATE PROJECT
OCESQL*        SET PROJ_NAME = :WS-PROJNAME,
OCESQL*            BUDGET = :WS-BUDGET
OCESQL*        WHERE PROJ_ID = :WS-PROJID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 60
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PROJNAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 12
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-BUDGET
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PROJID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
OCESQL*        EXEC SQL
OCESQL*            INSERT INTO PROJECT
OCESQL*            (PROJ_ID, PROJ_NAME, BUDGET)
OCESQL*            VALUES
OCESQL*            (:WS-PROJID, :WS-PROJNAME, :WS-BUDGET)
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PROJID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 60
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PROJNAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 12
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-BUDGET
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0004
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL
           END-IF.

       DALEND.
           IF WS-CURSOROPEN = 'Y'
OCESQL*        EXEC SQL
OCESQL*            CLOSE CPROJ
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPROJ" & x"00"
OCESQL     END-CALL
               MOVE 'N' TO WS-CURSOROPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.