       IDENTIFICATION DIVISION.
       PROGRAM-ID. CUSTOMER-DAL-DB.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-CURSOR-OPEN         PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WS-CUST-ID             PIC 9(9).
       01 WS-CUST-NAME           PIC X(40).
       01 WS-CUST-CITY           PIC X(30).
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(050) VALUE "SELECT CUST_ID, CUST_NAME, CUS"
OCESQL  &  "T_CITY FROM CUSTOMER".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(074) VALUE "INSERT INTO CUSTOMER (CUST_ID,"
OCESQL  &  " CUST_NAME, CUST_CITY) VALUES ( $1, $2, $3 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(069) VALUE "UPDATE CUSTOMER SET CUST_NAME "
OCESQL  &  "= $1, CUST_CITY = $2 WHERE CUST_ID = $3".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0005.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LK-OPERATION           PIC X(4).
       01 LK-END-OF-FILE         PIC X.
       01 LK-CUSTOMER.
           05 LK-CUST-ID         PIC 9(9).
           05 LK-CUST-NAME       PIC X(40).
           05 LK-CUST-CITY       PIC X(30).

       PROCEDURE DIVISION USING LK-OPERATION LK-END-OF-FILE
           LK-CUSTOMER.
       MAIN-LOGIC.
           EVALUATE LK-OPERATION
               WHEN 'READ'
                   PERFORM DALREAD
               WHEN 'SAVE'
                   PERFORM DALSAVE
               WHEN 'END '
                   PERFORM DALEND
           END-EVALUATE.
           EXIT PROGRAM.

       DALREAD.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

           IF WS-CURSOR-OPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CCUST CURSOR FOR
OCESQL*            SELECT CUST_ID, CUST_NAME, CUST_CITY
OCESQL*            FROM CUSTOMER
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorDeclare" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CCUST" & x"00"
OCESQL          BY REFERENCE SQ0002
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CCUST
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CCUST" & x"00"
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CCUST INTO
OCESQL*            :WS-CUST-ID,
OCESQL*            :WS-CUST-NAME,
OCESQL*            :WS-CUST-CITY
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 40
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-NAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 30
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-CITY
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CCUST" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           ELSE
               MOVE WS-CUST-ID     TO LK-CUST-ID
               MOVE WS-CUST-NAME   TO LK-CUST-NAME
               MOVE WS-CUST-CITY   TO LK-CUST-CITY
           END-IF.

       DALSAVE.
           MOVE LK-CUST-ID        TO WS-CUST-ID.
           MOVE LK-CUST-NAME      TO WS-CUST-NAME.
           MOVE LK-CUST-CITY      TO WS-CUST-CITY.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO CUSTOMER
OCESQL*        (CUST_ID, CUST_NAME, CUST_CITY)
OCESQL*        VALUES
OCESQL*        (:WS-CUST-ID, :WS-CUST-NAME, :WS-CUST-CITY)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 40
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-NAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 30
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-CITY
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
OCESQL*        EXEC SQL
OCESQL*            UPDATE CUSTOMER
OCESQL*            SET CUST_NAME = :WS-CUST-NAME,
OCESQL*                CUST_CITY = :WS-CUST-CITY
OCESQL*            WHERE CUST_ID = :WS-CUST-ID
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 40
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-NAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 30
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-CITY
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-CUST-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0004
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL
           END-IF.

       DALEND.
           IF WS-CURSOR-OPEN = 'Y'
OCESQL*        EXEC SQL
OCESQL*            CLOSE CCUST
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CCUST" & x"00"
OCESQL     END-CALL
               MOVE 'N' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.