       IDENTIFICATION DIVISION.
       PROGRAM-ID. TEST-ACTIVITY-DAL.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-OPERATION          PIC X(30).
      *    CORRECTION: AJOUT DE CE CHAMP
       01 WS-END-OF-FILE        PIC X VALUE 'N'.
       01 WS-USER.
           05 WSUSERID          PIC 9(9) VALUE 1.
           05 WSUSERNOM         PIC X(50) VALUE "TEST USER".
           05 WSUSERMAIL        PIC X(80) VALUE "test@user.com".
           05 WSUSERPASS        PIC X(256) VALUE "password".
           05 WSUSERROLE        PIC X(15) VALUE "MEMBRE".
           05 WSUSERIDANTENNE   PIC 9(9) VALUE 1.
           05 WSUSERLASTLOGIN   PIC 9(18) VALUE 0.
       01 WS-ACTIVITE.
           05 WSACTIVITEID      PIC 9(9) VALUE 1.
           05 WSACTIVITENOM     PIC X(50) VALUE "TEST ACTIVITE".
           05 WSACTIVITETYPE    PIC X(20) VALUE "SPORT".
           05 WSACTIVITEIDANTENNE PIC 9(9) VALUE 1.
           05 WSACTIVITEANIMATEUR PIC 9(9) VALUE 1.
           05 WSACTIVITENBPART  PIC 9(9) VALUE 0.
           05 WSACTIVITEMODETRANS PIC 9(9) VALUE 1.
           05 WSACTIVITELIEU    PIC X(100) VALUE "GYMNASE".
           05 WSACTIVITEDISTANCE PIC 9(9) VALUE 0.
           05 WSACTIVITEHEBERG  PIC 9(9) VALUE 0.
           05 WSACTIVITEREPAS   PIC 9(9) VALUE 0.
           05 WSACTIVITEEMPREINTE PIC 9(13)V9(4) VALUE 0.
       01 WS-PARTICIPATION.
           05 WSPARTACTIVITEID  PIC 9(9) VALUE 1.
           05 WSPARTUSERID      PIC 9(9) VALUE 1.
           05 WSPARTMODETRANS   PIC 9(9) VALUE 1.
       01 WS-JOINTURE.
           05 WSJOINTACTIVITEID PIC 9(9).
           05 WSJOINTACTIVITENOM PIC X(50).
           05 WSJOINTACTIVITETYPE PIC X(20).
           05 WSJOINTACTIVITELIEU PIC X(100).
           05 WSJOINUSERID      PIC 9(9).
           05 WSJOINUSERNOM     PIC X(50).
           05 WSJOINUSERMAIL    PIC X(80).
           05 WSJOINMODETRANS   PIC 9(9).
       01 WS-COUNT             PIC 9(3) VALUE 0.

       PROCEDURE DIVISION.
       MAIN-LOGIC.
           DISPLAY "TEST CREATEUSER".
           MOVE "CREATEUSER" TO WS-OPERATION
           CALL "ACTIVITY-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-USER WS-ACTIVITE WS-PARTICIPATION WS-JOINTURE.
           IF WS-END-OF-FILE = 'Y'
               DISPLAY "ERREUR CREATEUSER"
           ELSE
               DISPLAY "CREATEUSER OK".

           DISPLAY "TEST CREATEACTIVITE".
           MOVE "CREATEACTIVITE" TO WS-OPERATION
           CALL "ACTIVITY-DAL-DB" USING WS-OPERATION WS-END-OF-FILE
               WS-USER WS-ACTIVITE WS-PARTICIPATION WS-JOINTURE.
           IF WS-END-OF-FILE = 'Y'
               DISPLAY "ERREUR CREATEACTIVITE"
           ELSE
               DISPLAY "CREATEACTIVITE OK".

           DISPLAY "TEST CREATEPARTICIPATION".
           MOVE "CREATEPARTICIPATION" TO WS-OPERATION
           CALL "ACTIVITY-DAL-DB" USING WS-OPERATION
               WS-END-OF-FILE WS-USER WS-ACTIVITE WS-PARTICIPATION
               WS-JOINTURE.
           IF WS-END-OF-FILE = 'Y'
               DISPLAY "ERREUR CREATEPARTICIPATION"
           ELSE
               DISPLAY "CREATEPARTICIPATION OK".

           DISPLAY "TEST READPARTICIPATION".
           MOVE "READPARTICIPATION" TO WS-OPERATION
           CALL "ACTIVITY-DAL-DB" USING WS-OPERATION
               WS-END-OF-FILE WS-USER WS-ACTIVITE WS-PARTICIPATION
               WS-JOINTURE.
           IF WS-END-OF-FILE = 'Y'
               DISPLAY "ERREUR READPARTICIPATION"
           ELSE
               DISPLAY "READPARTICIPATION OK"
               CALL "DISPLAY-PARTICIPATION" USING WS-JOINTURE
                   WS-END-OF-FILE.

           DISPLAY "TEST LISTPARTBYACT".
           MOVE 'N' TO WS-END-OF-FILE.
           PERFORM UNTIL WS-END-OF-FILE = 'Y'
               MOVE "LISTPARTBYACT" TO WS-OPERATION
               CALL "ACTIVITY-DAL-DB" USING WS-OPERATION
                   WS-END-OF-FILE WS-USER WS-ACTIVITE WS-PARTICIPATION
                   WS-JOINTURE
               IF WS-END-OF-FILE = 'N'
                   CALL "DISPLAY-PARTICIPATION" USING WS-JOINTURE
                       WS-END-OF-FILE
                   ADD 1 TO WS-COUNT
               END-IF
           END-PERFORM.
           DISPLAY "LISTPARTBYACT OK - " WS-COUNT " ENREGISTREMENTS".

           DISPLAY "TEST LISTACTBYUSER".
           MOVE 1 TO WSPARTUSERID.
           MOVE 'N' TO WS-END-OF-FILE.
           MOVE 0 TO WS-COUNT.
           PERFORM UNTIL WS-END-OF-FILE = 'Y'
               MOVE "LISTACTBYUSER" TO WS-OPERATION
               CALL "ACTIVITY-DAL-DB" USING WS-OPERATION
                   WS-END-OF-FILE WS-USER WS-ACTIVITE WS-PARTICIPATION
                   WS-JOINTURE
               IF WS-END-OF-FILE = 'N'
                   CALL "DISPLAY-PARTICIPATION" USING WS-JOINTURE
                       WS-END-OF-FILE
                   ADD 1 TO WS-COUNT
               END-IF
           END-PERFORM.
           DISPLAY "LISTACTBYUSER OK - " WS-COUNT " ENREGISTREMENTS".

           DISPLAY "TEST UPDATEMODETRANS".
           MOVE 2 TO WSPARTMODETRANS.
           MOVE "UPDATEMODETRANS" TO WS-OPERATION
           CALL "ACTIVITY-DAL-DB" USING WS-OPERATION
               WS-END-OF-FILE WS-USER WS-ACTIVITE WS-PARTICIPATION
               WS-JOINTURE.
           IF WS-END-OF-FILE = 'Y'
               DISPLAY "ERREUR UPDATEMODETRANS"
           ELSE
               DISPLAY "UPDATEMODETRANS OK"
               MOVE "READPARTICIPATION" TO WS-OPERATION
               CALL "ACTIVITY-DAL-DB" USING WS-OPERATION
                   WS-END-OF-FILE WS-USER WS-ACTIVITE WS-PARTICIPATION
                   WS-JOINTURE
               CALL "DISPLAY-PARTICIPATION" USING WS-JOINTURE
                   WS-END-OF-FILE.

           DISPLAY "TEST DELETEPARTICIPATION".
           MOVE "DELETEPARTICIPATION" TO WS-OPERATION
           CALL "ACTIVITY-DAL-DB" USING "DELETEPARTICIPATION"
               WS-END-OF-FILE WS-USER WS-ACTIVITE WS-PARTICIPATION
               WS-JOINTURE.
           IF WS-END-OF-FILE = 'Y'
               DISPLAY "ERREUR DELETEPARTICIPATION"
           ELSE
               DISPLAY "DELETEPARTICIPATION OK"
               MOVE "READPARTICIPATION" TO WS-OPERATION
               CALL "ACTIVITY-DAL-DB" USING WS-OPERATION
                   WS-END-OF-FILE WS-USER WS-ACTIVITE WS-PARTICIPATION
                   WS-JOINTURE
               IF WS-END-OF-FILE = 'Y'
                   DISPLAY "VERIFICATION DELETE OK"
               ELSE
                   DISPLAY "ERREUR VERIFICATION DELETE".

           CALL "ACTIVITY-DAL-DB" USING "END" WS-END-OF-FILE
               WS-USER WS-ACTIVITE WS-PARTICIPATION WS-JOINTURE.
           STOP RUN.