       IDENTIFICATION DIVISION.
       PROGRAM-ID. EMPLOYEEDAL.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-CURSOR-OPEN         PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WS-EMPID               PIC 9(4).
       01 WS-EMPNAME             PIC X(30).
       01 WS-SALARYBRUT          PIC 9(6)V99.
       01 WS-SALARYNET           PIC 9(6)V99.
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(062) VALUE "SELECT EMP_ID, EMP_NAME, SALAR"
OCESQL  &  "Y_BRUT, SALARY_NET FROM EMPLOYEE".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(053) VALUE "UPDATE EMPLOYEE SET SALARY_NET"
OCESQL  &  " = $1 WHERE EMP_ID = $2".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LK-OPERATION           PIC X(4).
       01 LK-END-OF-FILE         PIC X.
       01 LK-EMPLOYEE.
           05 LK-EMPID           PIC 9(4).
           05 LK-EMPNAME         PIC X(30).
           05 LK-SALARYBRUT      PIC 9(6)V99.
           05 LK-SALARYNET       PIC 9(6)V99.

       PROCEDURE DIVISION USING LK-OPERATION LK-END-OF-FILE
           LK-EMPLOYEE.
       MAINLOGIC.
           EVALUATE LK-OPERATION
               WHEN 'READ'
                   PERFORM READPROC
               WHEN 'SAVE'
                   PERFORM SAVEPROC
               WHEN 'END '
                   PERFORM ENDPROC
           END-EVALUATE.
           EXIT PROGRAM.

       READPROC.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

           IF WS-CURSOR-OPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CEMP CURSOR FOR
OCESQL*            SELECT EMP_ID, EMP_NAME, SALARY_BRUT, SALARY_NET
OCESQL*            FROM EMPLOYEE
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorDeclare" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CEMP" & x"00"
OCESQL          BY REFERENCE SQ0002
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CEMP
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CEMP" & x"00"
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CEMP INTO
OCESQL*            :WS-EMPID,
OCESQL*            :WS-EMPNAME,
OCESQL*            :WS-SALARYBRUT,
OCESQL*            :WS-SALARYNET
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-EMPID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 30
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-EMPNAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-SALARYBRUT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-SALARYNET
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CEMP" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           ELSE
               MOVE WS-EMPID        TO LK-EMPID
               MOVE WS-EMPNAME      TO LK-EMPNAME
               MOVE WS-SALARYBRUT   TO LK-SALARYBRUT
               MOVE WS-SALARYNET    TO LK-SALARYNET
           END-IF.

       SAVEPROC.
           MOVE LK-EMPID        TO WS-EMPID.
           MOVE LK-SALARYNET    TO WS-SALARYNET.

OCESQL*    EXEC SQL
OCESQL*        UPDATE EMPLOYEE
OCESQL*        SET SALARY_NET = :WS-SALARYNET
OCESQL*        WHERE EMP_ID = :WS-EMPID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-SALARYNET
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-EMPID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 2
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

       ENDPROC.
           IF WS-CURSOR-OPEN = 'Y'
OCESQL*        EXEC SQL
OCESQL*            CLOSE CEMP
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CEMP" & x"00"
OCESQL     END-CALL
               MOVE 'N' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.