       IDENTIFICATION DIVISION.
       PROGRAM-ID. HEBERGEMENT-DAL-DB.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-CURSOR-OPEN         PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WS-HEBERGEMENT.
           05 WS-HEB-ID          PIC 9(9).
           05 WS-HEB-ID-ACT      PIC 9(9).
           05 WS-HEB-TYPE        PIC 9(4).
           05 WS-HEB-NBNUIT      PIC 9(4).
       01 WS-ACTIVITE.
           05 WS-ACT-ID          PIC 9(9).
           05 WS-ACT-NOM         PIC X(50).
           05 WS-ACT-TYPE        PIC X(20).
           05 WS-ACT-IDANTENNE   PIC 9(9).
           05 WS-ACT-ANIMATEUR   PIC 9(9).
           05 WS-ACT-NBPART      PIC 9(4).
           05 WS-ACT-MODETRANS   PIC 9(4).
           05 WS-ACT-LIEU        PIC X(100).
           05 WS-ACT-DISTANCE    PIC 9(9).
           05 WS-ACT-HEBERG      PIC 9(9).
           05 WS-ACT-REPAS       PIC 9(4).
           05 WS-ACT-EMPREINTE   PIC 9(13)V9(4).
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(129) VALUE "INSERT INTO HEBERGEMENT (HEBER"
OCESQL  &  "GEMENT_ID, HEBERGEMENT_ID_ACTIVITE, HEBERGEMENT_TYPE, HEBE"
OCESQL  &  "RGEMENT_NBNUIT) VALUES ( $1, $2, $3, $4 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(256) VALUE "INSERT INTO ACTIVITE (ACTIVITE"
OCESQL  &  "_ID, ACTIVITE_NOM, ACTIVITE_TYPE, ACTIVITE_IDANTENNE, ACTI"
OCESQL  &  "VITE_ANIMATEUR, ACTIVITE_NBPARTICIPANTS, ACTIVITE_MODETRAN"
OCESQL  &  "SPORT, ACTIVITE_LIEU, ACTIVITE_DISTANCE, ACTIVITE_HEBERGEM"
OCESQL  &  "ENT, ACTIVITE_REPASPREVU, ACTIVITE_EMPREINTETOTALE) ".
OCESQL     02  FILLER PIC X(060) VALUE "VALUES ( $1, $2, $3, $4, $5, $"
OCESQL  &  "6, $7, $8, $9, $10, $11, $12 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(068) VALUE "UPDATE ACTIVITE SET ACTIVITE_H"
OCESQL  &  "EBERGEMENT = $1 WHERE ACTIVITE_ID = $2".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0005.
OCESQL     02  FILLER PIC X(127) VALUE "SELECT HEBERGEMENT_ID, HEBERGE"
OCESQL  &  "MENT_ID_ACTIVITE, HEBERGEMENT_TYPE, HEBERGEMENT_NBNUIT FRO"
OCESQL  &  "M HEBERGEMENT WHERE HEBERGEMENT_ID = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0006.
OCESQL     02  FILLER PIC X(136) VALUE "SELECT HEBERGEMENT_ID, HEBERGE"
OCESQL  &  "MENT_ID_ACTIVITE, HEBERGEMENT_TYPE, HEBERGEMENT_NBNUIT FRO"
OCESQL  &  "M HEBERGEMENT WHERE HEBERGEMENT_ID_ACTIVITE = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0007.
OCESQL     02  FILLER PIC X(095) VALUE "UPDATE HEBERGEMENT SET HEBERGE"
OCESQL  &  "MENT_TYPE = $1, HEBERGEMENT_NBNUIT = $2 WHERE HEBERGEMENT_"
OCESQL  &  "ID = $3".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0008.
OCESQL     02  FILLER PIC X(049) VALUE "DELETE FROM HEBERGEMENT WHERE "
OCESQL  &  "HEBERGEMENT_ID = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0009.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LK-OPERATION           PIC X(10).
       01 LK-END-OF-FILE         PIC X.
       01 LK-HEBERGEMENT.
           05 LK-HEB-ID          PIC 9(9).
           05 LK-HEB-ID-ACT      PIC 9(9).
           05 LK-HEB-TYPE        PIC 9(4).
           05 LK-HEB-NBNUIT      PIC 9(4).
       01 LK-ACTIVITE.
           05 LK-ACT-ID          PIC 9(9).
           05 LK-ACT-NOM         PIC X(50).
           05 LK-ACT-TYPE        PIC X(20).
           05 LK-ACT-IDANTENNE   PIC 9(9).
           05 LK-ACT-ANIMATEUR   PIC 9(9).
           05 LK-ACT-NBPART      PIC 9(4).
           05 LK-ACT-MODETRANS   PIC 9(4).
           05 LK-ACT-LIEU        PIC X(100).
           05 LK-ACT-DISTANCE    PIC 9(9).
           05 LK-ACT-HEBERG      PIC 9(9).
           05 LK-ACT-REPAS       PIC 9(4).
           05 LK-ACT-EMPREINTE   PIC 9(13)V9(4).

       PROCEDURE DIVISION USING LK-OPERATION LK-END-OF-FILE
           LK-HEBERGEMENT LK-ACTIVITE.
       MAIN-LOGIC.
           EVALUATE LK-OPERATION
               WHEN 'CREATEHEB'
                   PERFORM CREATE-HEBERGEMENT
               WHEN 'CREATEACT'
                   PERFORM CREATE-ACTIVITE
               WHEN 'ADDACTHEB'
                   PERFORM ADD-ACTIVITE-HEBERGEMENT
               WHEN 'READHEB'
                   PERFORM READ-HEBERGEMENT
               WHEN 'LISTHEBACT'
                   PERFORM LIST-HEBERGEMENTS-ACTIVITE
               WHEN 'UPDATEHEB'
                   PERFORM UPDATE-HEBERGEMENT
               WHEN 'DELETEHEB'
                   PERFORM DELETE-HEBERGEMENT
               WHEN 'END'
                   PERFORM END-PROGRAM
           END-EVALUATE.
           EXIT PROGRAM.

       CONNECT-DB.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE = 0
                   MOVE 'Y' TO WS-CONNECTED
               ELSE
                   MOVE 'Y' TO LK-END-OF-FILE
               END-IF
           END-IF.

       CREATE-HEBERGEMENT.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LK-HEB-ID TO WS-HEB-ID.
           MOVE LK-HEB-ID-ACT TO WS-HEB-ID-ACT.
           MOVE LK-HEB-TYPE TO WS-HEB-TYPE.
           MOVE LK-HEB-NBNUIT TO WS-HEB-NBNUIT.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO HEBERGEMENT
OCESQL*        (HEBERGEMENT_ID, HEBERGEMENT_ID_ACTIVITE,
OCESQL*         HEBERGEMENT_TYPE, HEBERGEMENT_NBNUIT)
OCESQL*        VALUES
OCESQL*        (:WS-HEB-ID, :WS-HEB-ID-ACT, :WS-HEB-TYPE,
OCESQL*         :WS-HEB-NBNUIT)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID-ACT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-NBNUIT
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0002
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       CREATE-ACTIVITE.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LK-ACT-ID TO WS-ACT-ID.
           MOVE LK-ACT-NOM TO WS-ACT-NOM.
           MOVE LK-ACT-TYPE TO WS-ACT-TYPE.
           MOVE LK-ACT-IDANTENNE TO WS-ACT-IDANTENNE.
           MOVE LK-ACT-ANIMATEUR TO WS-ACT-ANIMATEUR.
           MOVE LK-ACT-NBPART TO WS-ACT-NBPART.
           MOVE LK-ACT-MODETRANS TO WS-ACT-MODETRANS.
           MOVE LK-ACT-LIEU TO WS-ACT-LIEU.
           MOVE LK-ACT-DISTANCE TO WS-ACT-DISTANCE.
           MOVE LK-ACT-HEBERG TO WS-ACT-HEBERG.
           MOVE LK-ACT-REPAS TO WS-ACT-REPAS.
           MOVE LK-ACT-EMPREINTE TO WS-ACT-EMPREINTE.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO ACTIVITE
OCESQL*        (ACTIVITE_ID, ACTIVITE_NOM, ACTIVITE_TYPE,
OCESQL*         ACTIVITE_IDANTENNE, ACTIVITE_ANIMATEUR,
OCESQL*         ACTIVITE_NBPARTICIPANTS, ACTIVITE_MODETRANSPORT,
OCESQL*         ACTIVITE_LIEU, ACTIVITE_DISTANCE, ACTIVITE_HEBERGEMENT,
OCESQL*         ACTIVITE_REPASPREVU, ACTIVITE_EMPREINTETOTALE)
OCESQL*        VALUES
OCESQL*        (:WS-ACT-ID, :WS-ACT-NOM, :WS-ACT-TYPE,
OCESQL*         :WS-ACT-IDANTENNE, :WS-ACT-ANIMATEUR,
OCESQL*         :WS-ACT-NBPART, :WS-ACT-MODETRANS,
OCESQL*         :WS-ACT-LIEU, :WS-ACT-DISTANCE, :WS-ACT-HEBERG,
OCESQL*         :WS-ACT-REPAS, :WS-ACT-EMPREINTE)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-NOM
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 20
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-IDANTENNE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-ANIMATEUR
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-NBPART
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-MODETRANS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 100
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-LIEU
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-DISTANCE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-HEBERG
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-REPAS
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 17
OCESQL          BY VALUE -4
OCESQL          BY REFERENCE WS-ACT-EMPREINTE
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 12
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       ADD-ACTIVITE-HEBERGEMENT.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LK-HEB-ID TO WS-HEB-ID.
           MOVE LK-ACT-ID TO WS-ACT-ID.

OCESQL*    EXEC SQL
OCESQL*        UPDATE ACTIVITE
OCESQL*        SET ACTIVITE_HEBERGEMENT = :WS-HEB-ID
OCESQL*        WHERE ACTIVITE_ID = :WS-ACT-ID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0004
OCESQL          BY VALUE 2
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       READ-HEBERGEMENT.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LK-HEB-ID TO WS-HEB-ID.

OCESQL*    EXEC SQL
OCESQL*        SELECT HEBERGEMENT_ID, HEBERGEMENT_ID_ACTIVITE,
OCESQL*               HEBERGEMENT_TYPE, HEBERGEMENT_NBNUIT
OCESQL*        INTO :WS-HEB-ID, :WS-HEB-ID-ACT, :WS-HEB-TYPE,
OCESQL*             :WS-HEB-NBNUIT
OCESQL*        FROM HEBERGEMENT
OCESQL*        WHERE HEBERGEMENT_ID = :WS-HEB-ID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID-ACT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-NBNUIT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecSelectIntoOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0005
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE = 0
               MOVE WS-HEB-ID TO LK-HEB-ID
               MOVE WS-HEB-ID-ACT TO LK-HEB-ID-ACT
               MOVE WS-HEB-TYPE TO LK-HEB-TYPE
               MOVE WS-HEB-NBNUIT TO LK-HEB-NBNUIT
           ELSE
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       LIST-HEBERGEMENTS-ACTIVITE.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LK-ACT-ID TO WS-ACT-ID.

           IF WS-CURSOR-OPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CHEB CURSOR FOR
OCESQL*            SELECT HEBERGEMENT_ID, HEBERGEMENT_ID_ACTIVITE,
OCESQL*                   HEBERGEMENT_TYPE, HEBERGEMENT_NBNUIT
OCESQL*            FROM HEBERGEMENT
OCESQL*            WHERE HEBERGEMENT_ID_ACTIVITE = :WS-ACT-ID
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ACT-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorDeclareParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CHEB" & x"00"
OCESQL          BY REFERENCE SQ0006
OCESQL          BY VALUE 1
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CHEB
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CHEB" & x"00"
OCESQL     END-CALL
               IF SQLCODE = 0
                   MOVE 'Y' TO WS-CURSOR-OPEN
               ELSE
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CHEB INTO
OCESQL*            :WS-HEB-ID, :WS-HEB-ID-ACT, :WS-HEB-TYPE,
OCESQL*            :WS-HEB-NBNUIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID-ACT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-NBNUIT
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CHEB" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE = 0
               MOVE WS-HEB-ID TO LK-HEB-ID
               MOVE WS-HEB-ID-ACT TO LK-HEB-ID-ACT
               MOVE WS-HEB-TYPE TO LK-HEB-TYPE
               MOVE WS-HEB-NBNUIT TO LK-HEB-NBNUIT
           ELSE
               MOVE 'Y' TO LK-END-OF-FILE
               IF WS-CURSOR-OPEN = 'Y'
OCESQL*            EXEC SQL
OCESQL*                CLOSE CHEB
OCESQL*            END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CHEB" & x"00"
OCESQL     END-CALL
                   MOVE 'N' TO WS-CURSOR-OPEN
               END-IF
           END-IF.

       UPDATE-HEBERGEMENT.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LK-HEB-ID TO WS-HEB-ID.
           MOVE LK-HEB-TYPE TO WS-HEB-TYPE.
           MOVE LK-HEB-NBNUIT TO WS-HEB-NBNUIT.

OCESQL*    EXEC SQL
OCESQL*        UPDATE HEBERGEMENT
OCESQL*        SET HEBERGEMENT_TYPE = :WS-HEB-TYPE,
OCESQL*            HEBERGEMENT_NBNUIT = :WS-HEB-NBNUIT
OCESQL*        WHERE HEBERGEMENT_ID = :WS-HEB-ID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-TYPE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 4
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-NBNUIT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0007
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       DELETE-HEBERGEMENT.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y' EXIT PARAGRAPH.

           MOVE LK-HEB-ID TO WS-HEB-ID.

OCESQL*    EXEC SQL
OCESQL*        DELETE FROM HEBERGEMENT
OCESQL*        WHERE HEBERGEMENT_ID = :WS-HEB-ID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-HEB-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0008
OCESQL          BY VALUE 1
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           END-IF.

       END-PROGRAM.
           IF WS-CURSOR-OPEN = 'Y'
OCESQL*        EXEC SQL
OCESQL*            CLOSE CHEB
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CHEB" & x"00"
OCESQL     END-CALL
               MOVE 'N' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.