       IDENTIFICATION DIVISION.
       PROGRAM-ID. PRODUCTDAL.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WS-PRODID              PIC 9(9).
       01 WS-PRODNAME            PIC X(50).
       01 WS-PRICEHT             PIC 9(6)V99.
       01 WS-PRICETTC            PIC 9(6)V99.
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(069) VALUE "SELECT PROD_NAME, PRICE_HT, PR"
OCESQL  &  "ICE_TTC FROM PRODUCT WHERE PROD_ID = $1".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(083) VALUE "UPDATE PRODUCT SET PROD_NAME ="
OCESQL  &  " $1, PRICE_HT = $2, PRICE_TTC = $3 WHERE PROD_ID = $4".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(087) VALUE "INSERT INTO PRODUCT (PROD_ID, "
OCESQL  &  "PROD_NAME, PRICE_HT, PRICE_TTC) VALUES ( $1, $2, $3, $4 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0005.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LK-OPERATION           PIC X(4).
       01 LK-END-OF-FILE         PIC X.
       01 LK-PRODUCT.
           05 LK-PRODID          PIC 9(9).
           05 LK-PRODNAME        PIC X(50).
           05 LK-PRICEHT         PIC 9(6)V99.
           05 LK-PRICETTC        PIC 9(6)V99.

       PROCEDURE DIVISION USING LK-OPERATION LK-END-OF-FILE
           LK-PRODUCT.
       MAIN-LOGIC.
           EVALUATE LK-OPERATION
               WHEN 'FIND'
                   PERFORM FIND-PRODUCT
               WHEN 'SAVE'
                   PERFORM SAVE-PRODUCT
               WHEN 'END '
                   PERFORM END-PROGRAM
           END-EVALUATE.
           EXIT PROGRAM.

       CONNECT-DB.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

       FIND-PRODUCT.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y'
               EXIT PARAGRAPH
           END-IF.

           MOVE LK-PRODID TO WS-PRODID.
OCESQL*    EXEC SQL
OCESQL*        SELECT PROD_NAME, PRICE_HT, PRICE_TTC
OCESQL*        INTO :WS-PRODNAME, :WS-PRICEHT, :WS-PRICETTC
OCESQL*        FROM PRODUCT
OCESQL*        WHERE PROD_ID = :WS-PRODID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PRODNAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-PRICEHT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-PRICETTC
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PRODID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecSelectIntoOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0002
OCESQL          BY VALUE 1
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           ELSE
               MOVE WS-PRODNAME    TO LK-PRODNAME
               MOVE WS-PRICEHT     TO LK-PRICEHT
               MOVE WS-PRICETTC    TO LK-PRICETTC
           END-IF.

       SAVE-PRODUCT.
           PERFORM CONNECT-DB.
           IF LK-END-OF-FILE = 'Y'
               EXIT PARAGRAPH
           END-IF.

           MOVE LK-PRODID      TO WS-PRODID.
           MOVE LK-PRODNAME    TO WS-PRODNAME.
           MOVE LK-PRICEHT     TO WS-PRICEHT.
           MOVE LK-PRICETTC    TO WS-PRICETTC.

OCESQL*    EXEC SQL
OCESQL*        UPDATE PRODUCT
OCESQL*        SET PROD_NAME = :WS-PRODNAME,
OCESQL*            PRICE_HT = :WS-PRICEHT,
OCESQL*            PRICE_TTC = :WS-PRICETTC
OCESQL*        WHERE PROD_ID = :WS-PRODID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PRODNAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-PRICEHT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-PRICETTC
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PRODID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
OCESQL*        EXEC SQL
OCESQL*            INSERT INTO PRODUCT
OCESQL*            (PROD_ID, PROD_NAME, PRICE_HT, PRICE_TTC)
OCESQL*            VALUES
OCESQL*            (:WS-PRODID, :WS-PRODNAME, :WS-PRICEHT,
OCESQL*             :WS-PRICETTC)
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PRODID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 50
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PRODNAME
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-PRICEHT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-PRICETTC
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0004
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL
           END-IF.

       END-PROGRAM.
OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.