       IDENTIFICATION DIVISION.
       PROGRAM-ID. DISPLAY-PAYMENT.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-DISPLAY-LINE.
          05 FILLER PIC X(10) VALUE "PAY ID: ".
          05 WS-PAY-ID-DISP PIC 9(9).
          05 FILLER PIC X(10) VALUE " ORDER ID: ".
          05 WS-ORDER-ID-DISP PIC 9(9).
          05 FILLER PIC X(10) VALUE " AMOUNT: ".
          05 WS-AMOUNT-DISP PIC ZZZZZ9.99.

       LINKAGE SECTION.
       01 LK-PAYMENT.
          05 LK-PAY-ID PIC 9(9).
          05 LK-ORDER-ID PIC 9(9).
          05 LK-PAY-AMOUNT PIC 9(6)V99.

       PROCEDURE DIVISION USING LK-PAYMENT.
       MAIN-LOGIC.
           MOVE LK-PAY-ID TO WS-PAY-ID-DISP.
           MOVE LK-ORDER-ID TO WS-ORDER-ID-DISP.
           MOVE LK-PAY-AMOUNT TO WS-AMOUNT-DISP.
           DISPLAY WS-DISPLAY-LINE.
           EXIT PROGRAM.