       IDENTIFICATION DIVISION.
       PROGRAM-ID. PAYMENT-DAL-DB.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-CURSOR-OPEN         PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WS-PAY-ID              PIC 9(9).
       01 WS-ORDER-ID            PIC 9(9).
       01 WS-PAY-AMOUNT          PIC 9(6)V99.
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(048) VALUE "SELECT PAY_ID, ORDER_ID, PAY_A"
OCESQL  &  "MOUNT FROM PAYMENT".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(072) VALUE "INSERT INTO PAYMENT (PAY_ID, O"
OCESQL  &  "RDER_ID, PAY_AMOUNT) VALUES ( $1, $2, $3 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LK-OPERATION           PIC X(4).
       01 LK-END-OF-FILE         PIC X.
       01 LK-PAYMENT.
           05 LK-PAY-ID          PIC 9(9).
           05 LK-ORDER-ID        PIC 9(9).
           05 LK-PAY-AMOUNT      PIC 9(6)V99.

       PROCEDURE DIVISION USING LK-OPERATION LK-END-OF-FILE
           LK-PAYMENT.
       MAIN-LOGIC.
           EVALUATE LK-OPERATION
               WHEN 'READ'
                   PERFORM DALREAD
               WHEN 'SAVE'
                   PERFORM DALSAVE
               WHEN 'END '
                   PERFORM DALEND
           END-EVALUATE.
           EXIT PROGRAM.

       DALREAD.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

           IF WS-CURSOR-OPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CPAY CURSOR FOR
OCESQL*            SELECT PAY_ID, ORDER_ID, PAY_AMOUNT
OCESQL*            FROM PAYMENT
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorDeclare" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPAY" & x"00"
OCESQL          BY REFERENCE SQ0002
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CPAY
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPAY" & x"00"
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LK-END-OF-FILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CPAY INTO
OCESQL*            :WS-PAY-ID,
OCESQL*            :WS-ORDER-ID,
OCESQL*            :WS-PAY-AMOUNT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PAY-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ORDER-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-PAY-AMOUNT
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPAY" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LK-END-OF-FILE
           ELSE
               MOVE WS-PAY-ID      TO LK-PAY-ID
               MOVE WS-ORDER-ID    TO LK-ORDER-ID
               MOVE WS-PAY-AMOUNT  TO LK-PAY-AMOUNT
           END-IF.

       DALSAVE.
           MOVE LK-PAY-ID      TO WS-PAY-ID.
           MOVE LK-ORDER-ID    TO WS-ORDER-ID.
           MOVE LK-PAY-AMOUNT  TO WS-PAY-AMOUNT.

           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        INSERT INTO PAYMENT (PAY_ID, ORDER_ID, PAY_AMOUNT)
OCESQL*        VALUES (:WS-PAY-ID, :WS-ORDER-ID, :WS-PAY-AMOUNT)
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-PAY-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WS-ORDER-ID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 8
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WS-PAY-AMOUNT
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 3
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

       DALEND.
           IF WS-CURSOR-OPEN = 'Y'
OCESQL*        EXEC SQL
OCESQL*            CLOSE CPAY
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CPAY" & x"00"
OCESQL     END-CALL
               MOVE 'N' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.