       IDENTIFICATION DIVISION.
       PROGRAM-ID. INVOICE-DAL-DB.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. IBM-PC.
       OBJECT-COMPUTER. IBM-PC.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 WS-CONNECTED           PIC X VALUE 'N'.
       01 WS-CURSOR-OPEN         PIC X VALUE 'N'.
       01 WS-SQLCODE             PIC S9(9) COMP-5.

OCESQL*EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 DBNAME                 PIC X(30) VALUE 'postgres'.
       01 USERNAME               PIC X(30) VALUE 'postgres'.
       01 PASSWD                 PIC X(30) VALUE 'postgres'.
       01 WSINVID                PIC 9(9).
       01 WSINVDATE              PIC X(10).
       01 WSTOTALHT              PIC 9(7)V99.
       01 WSTOTALTTC             PIC 9(7)V99.
OCESQL*EXEC SQL END DECLARE SECTION END-EXEC.

OCESQL*EXEC SQL INCLUDE SQLCA END-EXEC.
OCESQL     copy "sqlca.cbl".

OCESQL*
OCESQL 01  SQ0001.
OCESQL     02  FILLER PIC X(031) VALUE "SET client_encoding TO 'LATIN1"
OCESQL  &  "'".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0002.
OCESQL     02  FILLER PIC X(057) VALUE "SELECT INV_ID, INV_DATE, TOTAL"
OCESQL  &  "_HT, TOTAL_TTC FROM INVOICE".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0003.
OCESQL     02  FILLER PIC X(081) VALUE "UPDATE INVOICE SET INV_DATE = "
OCESQL  &  "$1, TOTAL_HT = $2, TOTAL_TTC = $3 WHERE INV_ID = $4".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0004.
OCESQL     02  FILLER PIC X(085) VALUE "INSERT INTO INVOICE (INV_ID, I"
OCESQL  &  "NV_DATE, TOTAL_HT, TOTAL_TTC) VALUES ( $1, $2, $3, $4 )".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
OCESQL 01  SQ0005.
OCESQL     02  FILLER PIC X(014) VALUE "DISCONNECT ALL".
OCESQL     02  FILLER PIC X(1) VALUE X"00".
OCESQL*
       LINKAGE SECTION.
       01 LKOPERATION            PIC X(4).
       01 LKENDOFFILE            PIC X.
       01 LKINVOICE.
           05 LKINVID            PIC 9(9).
           05 LKINVDATE          PIC X(10).
           05 LKTOTALHT          PIC 9(7)V99.
           05 LKTOTALTTC         PIC 9(7)V99.

       PROCEDURE DIVISION USING LKOPERATION LKENDOFFILE
           LKINVOICE.
       MAINLOGIC.
           EVALUATE LKOPERATION
               WHEN 'READ'
                   PERFORM DALREAD
               WHEN 'SAVE'
                   PERFORM DALSAVE
               WHEN 'END '
                   PERFORM DALEND
           END-EVALUATE.
           EXIT PROGRAM.

       DALREAD.
           IF WS-CONNECTED = 'N'
OCESQL*        EXEC SQL
OCESQL*            CONNECT :USERNAME IDENTIFIED BY :PASSWD USING :DBNAME
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLConnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE USERNAME
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE PASSWD
OCESQL          BY VALUE 30
OCESQL          BY REFERENCE DBNAME
OCESQL          BY VALUE 30
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            SET client_encoding TO 'LATIN1'
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0001
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LKENDOFFILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CONNECTED
           END-IF.

           IF WS-CURSOR-OPEN = 'N'
OCESQL*        EXEC SQL
OCESQL*            DECLARE CINV CURSOR FOR
OCESQL*            SELECT INV_ID, INV_DATE, TOTAL_HT, TOTAL_TTC
OCESQL*            FROM INVOICE
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorDeclare" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CINV" & x"00"
OCESQL          BY REFERENCE SQ0002
OCESQL     END-CALL
OCESQL*        EXEC SQL
OCESQL*            OPEN CINV
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorOpen" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CINV" & x"00"
OCESQL     END-CALL
               IF SQLCODE NOT = 0
                   MOVE 'Y' TO LKENDOFFILE
                   EXIT PARAGRAPH
               END-IF
               MOVE 'Y' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        FETCH CINV INTO
OCESQL*            :WSINVID,
OCESQL*            :WSINVDATE,
OCESQL*            :WSTOTALHT,
OCESQL*            :WSTOTALTTC
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSINVID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 10
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSINVDATE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WSTOTALHT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetResultParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WSTOTALTTC
OCESQL     END-CALL
OCESQL     CALL "OCESQLCursorFetchOne" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CINV" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
               MOVE 'Y' TO LKENDOFFILE
           ELSE
               MOVE WSINVID        TO LKINVID
               MOVE WSINVDATE      TO LKINVDATE
               MOVE WSTOTALHT      TO LKTOTALHT
               MOVE WSTOTALTTC     TO LKTOTALTTC
           END-IF.

       DALSAVE.
           MOVE LKINVID        TO WSINVID.
           MOVE LKINVDATE      TO WSINVDATE.
           MOVE LKTOTALHT      TO WSTOTALHT.
           MOVE LKTOTALTTC     TO WSTOTALTTC.

OCESQL*    EXEC SQL
OCESQL*        UPDATE INVOICE
OCESQL*        SET INV_DATE = :WSINVDATE,
OCESQL*            TOTAL_HT = :WSTOTALHT,
OCESQL*            TOTAL_TTC = :WSTOTALTTC
OCESQL*        WHERE INV_ID = :WSINVID
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 10
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSINVDATE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WSTOTALHT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WSTOTALTTC
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSINVID
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0003
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF SQLCODE NOT = 0
OCESQL*        EXEC SQL
OCESQL*            INSERT INTO INVOICE
OCESQL*            (INV_ID, INV_DATE, TOTAL_HT, TOTAL_TTC)
OCESQL*            VALUES
OCESQL*            (:WSINVID, :WSINVDATE, :WSTOTALHT, :WSTOTALTTC)
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSINVID
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 16
OCESQL          BY VALUE 10
OCESQL          BY VALUE 0
OCESQL          BY REFERENCE WSINVDATE
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WSTOTALHT
OCESQL     END-CALL
OCESQL     CALL "OCESQLSetSQLParams" USING
OCESQL          BY VALUE 1
OCESQL          BY VALUE 9
OCESQL          BY VALUE -2
OCESQL          BY REFERENCE WSTOTALTTC
OCESQL     END-CALL
OCESQL     CALL "OCESQLExecParams" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE SQ0004
OCESQL          BY VALUE 4
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL
           END-IF.

       DALEND.
           IF WS-CURSOR-OPEN = 'Y'
OCESQL*        EXEC SQL
OCESQL*            CLOSE CINV
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLCursorClose"  USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "DAL_CINV" & x"00"
OCESQL     END-CALL
               MOVE 'N' TO WS-CURSOR-OPEN
           END-IF.

OCESQL*    EXEC SQL
OCESQL*        COMMIT
OCESQL*    END-EXEC.
OCESQL     CALL "OCESQLStartSQL"
OCESQL     END-CALL
OCESQL     CALL "OCESQLExec" USING
OCESQL          BY REFERENCE SQLCA
OCESQL          BY REFERENCE "COMMIT" & x"00"
OCESQL     END-CALL
OCESQL     CALL "OCESQLEndSQL"
OCESQL     END-CALL.

           IF WS-CONNECTED = 'Y'
OCESQL*        EXEC SQL
OCESQL*            DISCONNECT ALL
OCESQL*        END-EXEC
OCESQL     CALL "OCESQLDisconnect" USING
OCESQL          BY REFERENCE SQLCA
OCESQL     END-CALL
               MOVE 'N' TO WS-CONNECTED
           END-IF.